"""empty message

Revision ID: 0f653d9fefa8
Revises: 7b9a357c7246
Create Date: 2024-03-15 17:23:59.941761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f653d9fefa8'
down_revision = '7b9a357c7246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yg_pro_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('frameType', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cards', schema=None) as batch_op:
        batch_op.drop_column('frameType')
        batch_op.drop_column('yg_pro_id')

    # ### end Alembic commands ###
