"""unique constrants check

Revision ID: 642cfce71466
Revises: 6c189548d696
Create Date: 2024-08-11 21:03:54.177365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642cfce71466'
down_revision = '6c189548d696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Decks', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Decks_user_id'), ['user_id', 'name'])

    with op.batch_alter_table('RefreshTokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_RefreshTokens_user_id'), ['user_id'])

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Users_email'), type_='unique')

    with op.batch_alter_table('RefreshTokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_RefreshTokens_user_id'), type_='unique')

    with op.batch_alter_table('Decks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Decks_user_id'), type_='unique')

    # ### end Alembic commands ###
