"""empty message

Revision ID: 6c189548d696
Revises: e619e51a45d8
Create Date: 2024-05-07 14:43:53.092426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c189548d696'
down_revision = 'e619e51a45d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RefreshTokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.UUID(), nullable=True),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_RefreshTokens_user_id_Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_RefreshTokens'))
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True))

    op.drop_table('RefreshTokens')
    # ### end Alembic commands ###
