"""added constraint for Inventory to prevent duplicates

Revision ID: b73fa06cf210
Revises: fe7407ec9979
Create Date: 2024-08-23 13:43:48.090877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73fa06cf210'
down_revision = 'fe7407ec9979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Inventories_isFirstEd'), ['isFirstEd','user_id','cardinSet_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Inventories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Inventories_isFirstEd'),type_='unique')


    # ### end Alembic commands ###
