"""Contstraint where a single deck cannot have multiple copies of the same card in the same location and quantity != 0

Revision ID: fe7407ec9979
Revises: 642cfce71466
Create Date: 2024-08-12 14:06:48.885594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7407ec9979'
down_revision = '642cfce71466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CardsinDecks', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_CardsinDecks_deck_id'),['deck_id','card_id','location'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CardsinDecks', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_CardsinDecks_deck_id'),type_='unique')
    # ### end Alembic commands ###
